# Generated by Django 6.0.2 on 2026-03-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('course', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
